export const QUERIES = new Map([
	['sm', '@media screen and (max-width: 599px)'],
	['md', '@media screen and (min-width: 600px) and (max-width: 959px)'],
	['lg', '@media screen and (min-width: 960px)'],
	['light', '@media (prefers-color-scheme: light)'],
	['dark', '@media (prefers-color-scheme: dark)'],
	['@3xs', '@container (width >= 256px)'],
	['@2xs', '@container (width >= 288px)'],
	['@xs', '@container (width >= 320px)'],
	['@sm', '@container (width >= 384px)'],
	['@md', '@container (width >= 448px)'],
	['@lg', '@container (width >= 512px)'],
	['@xl', '@container (width >= 576px)'],
	['@2xl', '@container (width >= 672px)'],
	['@3xl', '@container (width >= 768px)'],
	['@4xl', '@container (width >= 896px)'],
	['@5xl', '@container (width >= 1024px)'],
	['@6xl', '@container (width >= 1152px)'],
	['@7xl', '@container (width >= 1280px)'],
])
